using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using Assets.Scripts;

public class World : MonoBehaviour
{
  public static Person pessoa;
  public static Week week;
  public static User usuario;

  public static Subject cHumans;
  public static Subject cNature;
  public static Subject cMath;
  public static Subject cLanguages;

  public static List<Content> cont_cHumans = new List<Content>();
  public static List<Content> cont_cNature = new List<Content>();
  public static List<Content> cont_Math = new List<Content>();
  public static List<Content> cont_Languages = new List<Content>();

  static World()
  {
    PopulatingPerson();
    PopulatingWeek();
    PopulatingUser();
    PopulatingCHumans();
    PopulatingCNature();
    PopulatingCMath();
    PopulatingLanguages();
    PopulatingSubjects();
  }

  public static void PopulatingPerson()
  {
    pessoa = new Person("Name Empty", "Course Empty", "Insti Empty");
  }
  public static void PopulatingWeek()
  {
    week = new Week(true,true,true,true,true,false,false,5);
  }
  public static void PopulatingSubjects()
  {
    cHumans = new Subject(1,"Ciências Humanas",cont_cHumans);
    cNature = new Subject(2, "Ciências da Natureza",cont_cNature);
    cMath = new Subject(3, "Matemática e suas Tecnologias",cont_Math);
    cLanguages = new Subject(4, "Linguagens, Códigos e suas Tecnologias",cont_Languages);
  }

  public static void PopulatingUser()
  {
    usuario = new User(pessoa, week, 1, 86, 92,0,1);
  }

  public static void PopulatingCHumans()
  {
    cont_cHumans.Add(new Content(1, "História", "Pré-História", 2));
    cont_cHumans.Add(new Content(1, "História", "Grécia Antiga", 2));
    cont_cHumans.Add(new Content(1, "História", "Roma Antiga", 2));
    cont_cHumans.Add(new Content(1, "História", "História do Islamismo", 2));
    cont_cHumans.Add(new Content(1, "História", "Maias, Incas e Astecas", 2));
    cont_cHumans.Add(new Content(1, "História", "Alta Idade Média: Império Bizantino", 2));
    cont_cHumans.Add(new Content(1, "História", "Carlos Magno e seu Império", 2));
    cont_cHumans.Add(new Content(1, "História", "Catolicismo na Idade Média", 2));
    cont_cHumans.Add(new Content(1, "História", "Feudalismo", 2));
    cont_cHumans.Add(new Content(1, "História", "Formação dos Estados Nacionais Europeus", 2));
    cont_cHumans.Add(new Content(1, "História", "Renascimento", 2));
    cont_cHumans.Add(new Content(1, "História", "Reformas Religiosas", 2));
    cont_cHumans.Add(new Content(1, "História", "Expansão Marítimo Comercial Europeia", 2));
    cont_cHumans.Add(new Content(1, "História", "Mercantilismo e Colonização das Américas", 2));
    cont_cHumans.Add(new Content(1, "História", "Absolutismo: Teorias e Governos", 2));
    cont_cHumans.Add(new Content(1, "História", "Revolução Inglesa do Século XVII", 2));
    cont_cHumans.Add(new Content(1, "História", "Iluminismo", 2));
    cont_cHumans.Add(new Content(1, "História", "EUA: Colonização e Independência", 2));
    cont_cHumans.Add(new Content(1, "História", "Revolução Francesa", 2));
    cont_cHumans.Add(new Content(1, "História", "Império de Napoleão e o Congresso de Viena", 2));
    cont_cHumans.Add(new Content(1, "História", "Independência das Colônias da América", 2));
    cont_cHumans.Add(new Content(1, "História", "Revoluções na França", 2));
    cont_cHumans.Add(new Content(1, "História", "Revolução Industrial", 2));
    cont_cHumans.Add(new Content(1, "História", "Liberalismo, Socialismo e Anarquismo", 2));
    cont_cHumans.Add(new Content(1, "História", "Guerra de Secessão dos Estados Unidos", 2));
    cont_cHumans.Add(new Content(1, "História", "Imperialismo Ásia e África", 2));
    cont_cHumans.Add(new Content(1, "História", "Primeira Guerra Mundial", 2));
    cont_cHumans.Add(new Content(1, "História", "Revolução Russa e o Governo de Stalin", 2));
    cont_cHumans.Add(new Content(1, "História", "Nazi-Facismo", 2));
    cont_cHumans.Add(new Content(1, "História", "Crise de 1929 e a Grande Depressão", 2));
    cont_cHumans.Add(new Content(1, "História", "Segunda Guerra Mundial e A Guerra Civil Espanhola", 2));
    cont_cHumans.Add(new Content(1, "História", "Holocausto", 2));
    cont_cHumans.Add(new Content(1, "História", "Guerra Fria", 2));
    cont_cHumans.Add(new Content(1, "História", "União Soviética", 2));
    cont_cHumans.Add(new Content(1, "História", "Conflito Árabe-Israelense", 2));
    cont_cHumans.Add(new Content(1, "História", "América Latina no Século XX", 2));
    cont_cHumans.Add(new Content(1, "História", "Queda do muro de Berlim", 2));
    cont_cHumans.Add(new Content(1, "História", "Fim da Guerra Fria", 2));
    cont_cHumans.Add(new Content(1, "História", "Descolonização", 2));
    cont_cHumans.Add(new Content(1, "História", "África do Sul e o Apartheid", 2));
    cont_cHumans.Add(new Content(1, "História", "EUA Pós-Segunda Guerra", 2));
    cont_cHumans.Add(new Content(1, "História", "Brasil Pré-Colonial", 2));
    cont_cHumans.Add(new Content(1, "História", "Colonização do Brasil", 2));
    cont_cHumans.Add(new Content(1, "História", "A Sociedade Colonial", 2));
    cont_cHumans.Add(new Content(1, "História", "A Formação Territorial do Brasil", 2));
    cont_cHumans.Add(new Content(1, "História", "Estrada e Bandeiras", 2));
    cont_cHumans.Add(new Content(1, "História", "Ciclo do Ouro", 2));
    cont_cHumans.Add(new Content(1, "História", "Revoltas Coloniais", 2));
    cont_cHumans.Add(new Content(1, "História", "Processo de Independência do Brasil", 2));
    cont_cHumans.Add(new Content(1, "História", "Primeiro Reinado", 2));
    cont_cHumans.Add(new Content(1, "História", "Período Regencial (1831-1840)", 2));
    cont_cHumans.Add(new Content(1, "História", "Segundo Reinado: D. Pedro II", 2));
    cont_cHumans.Add(new Content(1, "História", "Economia Cafeeira", 2));
    cont_cHumans.Add(new Content(1, "História", "Política Externa do Segundo Reinado", 2));
    cont_cHumans.Add(new Content(1, "História", "Proclamação da República", 2));
    cont_cHumans.Add(new Content(1, "História", "República da Espada (1889-1894)", 2));
    cont_cHumans.Add(new Content(1, "História", "República Oligárquica (1894-1930)", 2));
    cont_cHumans.Add(new Content(1, "História", "Crise da República Oligárquica", 2));
    cont_cHumans.Add(new Content(1, "História", "Era Vargas: Estado Novo", 2));
    cont_cHumans.Add(new Content(1, "História", "Governo de Vargas (1951-1954)", 2));
    cont_cHumans.Add(new Content(1, "História", "Governo de Juscelino Kubitschek", 2));
    cont_cHumans.Add(new Content(1, "História", "Governo de Jânio Quadros e Jango", 2));
    cont_cHumans.Add(new Content(1, "História", "Ditadura Militar", 2));
    cont_cHumans.Add(new Content(1, "História", "Governo Médici", 2));
    cont_cHumans.Add(new Content(1, "História", "Governo Geisel e Figueiredo", 2));
    cont_cHumans.Add(new Content(1, "História", "Fim do Regime Militar e Eleição de Tancredo", 2));
    cont_cHumans.Add(new Content(1, "História", "Nova República", 2));
    cont_cHumans.Add(new Content(1, "História", "Governo de Itamar Franco e FHC", 2));
    cont_cHumans.Add(new Content(1, "História", "Governo do Lula", 2));
    cont_cHumans.Add(new Content(1, "História", "Governo de Dilma Rousseff", 2));
    cont_cHumans.Add(new Content(1, "História", "Impeachment de Dilma Rousseff", 2));
    cont_cHumans.Add(new Content(1, "História", "Operação Lava Jato", 2));
    cont_cHumans.Add(new Content(1, "História", "Governo de Bolsonaro e Covid-19 no Brasil", 2));
    cont_cHumans.Add(new Content(1, "História", "Covid-19 Vacinas no mundo e no Brasil", 2));
    cont_cHumans.Add(new Content(2, "Geografia", "Conceitos de Geografia", 2));
    cont_cHumans.Add(new Content(2, "Geografia", "Cartografia", 2));
    cont_cHumans.Add(new Content(2, "Geografia", "Coordenadas Geográficas", 2));
    cont_cHumans.Add(new Content(2, "Geografia", "Movimentos da Terra", 2));
    cont_cHumans.Add(new Content(2, "Geografia", "Fusos Horário", 2));
    cont_cHumans.Add(new Content(2, "Geografia", "Lua, Eclipse Solar e Lunar", 2));
    cont_cHumans.Add(new Content(2, "Geografia", "Origem da Terra", 2));
    cont_cHumans.Add(new Content(2, "Geografia", "Geologia do Brasil", 2));
    cont_cHumans.Add(new Content(2, "Geografia", "Tipos de Solos", 2));
    cont_cHumans.Add(new Content(2, "Geografia", "Solos do Brasil", 2));
    cont_cHumans.Add(new Content(2, "Geografia", "Relevo: Agentes Formadores do Relevo", 2));
    cont_cHumans.Add(new Content(2, "Geografia", "Relevo Brasileiro", 2));
    cont_cHumans.Add(new Content(2, "Geografia", "Clima e Elementos Climáticos", 2));
    cont_cHumans.Add(new Content(2, "Geografia", "Tipos de Clima no Brasil", 2));
    cont_cHumans.Add(new Content(2, "Geografia", "Hidrografia", 2));
    cont_cHumans.Add(new Content(2, "Geografia", "Hidrografia do Brasil", 2));
    cont_cHumans.Add(new Content(2, "Geografia", "Vegetação: Formações Vegetais", 2));
    cont_cHumans.Add(new Content(2, "Geografia", "Vegetação do Brasil", 2));
    cont_cHumans.Add(new Content(2, "Geografia", "Desenvolvimento Sustentável e os Impactos Ambientais", 2));
    cont_cHumans.Add(new Content(2, "Geografia", "Poluição da Água: Conservação dos Solos", 2));
    cont_cHumans.Add(new Content(2, "Geografia", "Problemas Ambientais no Brasil", 2));
    cont_cHumans.Add(new Content(2, "Geografia", "População", 2));
    cont_cHumans.Add(new Content(2, "Geografia", "Problemas das Populações do Planeta", 2));
    cont_cHumans.Add(new Content(2, "Geografia", "População Brasileira", 2));
    cont_cHumans.Add(new Content(2, "Geografia", "População Economicamente Ativas e a Terceirização", 2));
    cont_cHumans.Add(new Content(2, "Geografia", "Distribuição de Renda, Emprego e Desemprego no Brasil", 2));
    cont_cHumans.Add(new Content(2, "Geografia", "Migrações: Movimentos Populacionais", 2));
    cont_cHumans.Add(new Content(2, "Geografia", "Migração Interna no Brasil", 2));
    cont_cHumans.Add(new Content(2, "Geografia", "Imigração no Brasil", 2));
    cont_cHumans.Add(new Content(2, "Geografia", "Os povos Indígenas no Brasil", 2));
    cont_cHumans.Add(new Content(2, "Geografia", "Urbanização", 2));
    cont_cHumans.Add(new Content(2, "Geografia", "Urbanização no Brasil", 2));
    cont_cHumans.Add(new Content(2, "Geografia", "Tipos de Indústria", 2));
    cont_cHumans.Add(new Content(2, "Geografia", "Localização Industrial no Brasil", 2));
    cont_cHumans.Add(new Content(2, "Geografia", "Extração e Energia Não Renovável", 2));
    cont_cHumans.Add(new Content(2, "Geografia", "Extrativismo Mineral no Brasil", 2));
    cont_cHumans.Add(new Content(2, "Geografia", "Fontes Renováveis de Energia", 2));
    cont_cHumans.Add(new Content(2, "Geografia", "Fontes de Energia", 2));
    cont_cHumans.Add(new Content(2, "Geografia", "Meios de Transporte", 2));
    cont_cHumans.Add(new Content(2, "Geografia", "Comunicações: Telecomunicações e Internet", 2));
    cont_cHumans.Add(new Content(2, "Geografia", "Meios de Transporte e Comunicação", 2));
    cont_cHumans.Add(new Content(2, "Geografia", "Espaço Geográfico", 2));
    cont_cHumans.Add(new Content(2, "Geografia", "Divisão Regional Brasileira", 2));
    cont_cHumans.Add(new Content(2, "Geografia", "Regiões Geoeconômicas", 2));
    cont_cHumans.Add(new Content(2, "Geografia", "Capitalismo e Socialismo", 2));
    cont_cHumans.Add(new Content(2, "Geografia", "Segunda Revolução Industrial", 2));
    cont_cHumans.Add(new Content(2, "Geografia", "Terceira Revolução Industrial", 2));
    cont_cHumans.Add(new Content(2, "Geografia", "Nova Ordem Mundial", 2));
    cont_cHumans.Add(new Content(2, "Geografia", "Organizações Internacionais", 2));
    cont_cHumans.Add(new Content(2, "Geografia", "Países Desenvolvidos e Subdesenvolvidos", 2));
    cont_cHumans.Add(new Content(2, "Geografia", "IDH no Brasil", 2));
    cont_cHumans.Add(new Content(2, "Geografia", "Neoliberalismo", 2));
    cont_cHumans.Add(new Content(2, "Geografia", "Blocos Econômicos", 2));
    cont_cHumans.Add(new Content(2, "Geografia", "União Europeia", 2));
    cont_cHumans.Add(new Content(2, "Geografia", "Política Econômica Brasileira", 2));
    cont_cHumans.Add(new Content(2, "Geografia", "África", 2));
    cont_cHumans.Add(new Content(2, "Geografia", "Europa", 2));
    cont_cHumans.Add(new Content(2, "Geografia", "Estados Unidos, Canadá e México", 2));
    cont_cHumans.Add(new Content(2, "Geografia", "América Latina", 2));
    cont_cHumans.Add(new Content(2, "Geografia", "Subcontinente Indiano", 2));
    cont_cHumans.Add(new Content(2, "Geografia", "China", 2));
    cont_cHumans.Add(new Content(2, "Geografia", "Geografia do Oriente Médio", 2));
    cont_cHumans.Add(new Content(2, "Geografia", "Estado, País e Nação: Conflitos Regionais", 2));
    cont_cHumans.Add(new Content(2, "Geografia", "Fundamentalismo Islâmico e o Terrorismo", 2));
    cont_cHumans.Add(new Content(2, "Geografia", "Sistemas Agrícolas", 2));
    cont_cHumans.Add(new Content(2, "Geografia", "Alimentos Transgênicos", 2));
    cont_cHumans.Add(new Content(2, "Geografia", "Agricultura Brasileira", 2));
    cont_cHumans.Add(new Content(2, "Geografia", "Estrutura Fundiária do Brasil", 2));
    cont_cHumans.Add(new Content(2, "Geografia", "Reforma Agrária", 2));
    cont_cHumans.Add(new Content(2, "Geografia", "Produção Agrária Brasileira", 2));
    cont_cHumans.Add(new Content(2, "Geografia", "Pecuária Brasileira", 2));
    cont_cHumans.Add(new Content(2, "Geografia", "Pecuária América Latina", 2));
    cont_cHumans.Add(new Content(2, "Geografia", "Agricultura ao Redor do Mundo", 2));
    cont_cHumans.Add(new Content(2, "Geografia", "Pecuária ao Redor do Mundo", 2));
    cont_cHumans.Add(new Content(2, "Geografia", "Problemas da Agropecuária", 2));
    cont_cHumans.Add(new Content(3, "Sociologia", "Processos Sociais", 2));
    cont_cHumans.Add(new Content(3, "Sociologia", "Sociedade", 2));
    cont_cHumans.Add(new Content(3, "Sociologia", "Cidadania Brasileira", 2));
    cont_cHumans.Add(new Content(3, "Sociologia", "Grupos Sociais", 2));
    cont_cHumans.Add(new Content(3, "Sociologia", "Cultura", 2));
    cont_cHumans.Add(new Content(3, "Sociologia", "Cultura no Brasil", 2));
    cont_cHumans.Add(new Content(3, "Sociologia", "Desvio e Criminalidade", 2));
    cont_cHumans.Add(new Content(3, "Sociologia", "Comportamento e Movimentos Social", 2));
    cont_cHumans.Add(new Content(3, "Sociologia", "Estratificação Social", 2));
    cont_cHumans.Add(new Content(3, "Sociologia", "Pobreza", 2));
    cont_cHumans.Add(new Content(3, "Sociologia", "Minorias", 2));
    cont_cHumans.Add(new Content(3, "Sociologia", "Desigualdade de Gênero", 2));
    cont_cHumans.Add(new Content(3, "Sociologia", "Religião", 2));
    cont_cHumans.Add(new Content(3, "Sociologia", "Instituições Sociais: Governo", 2));
    cont_cHumans.Add(new Content(3, "Sociologia", "Organização do Estado Brasileiro", 2));
    cont_cHumans.Add(new Content(3, "Sociologia", "Base Econômica da Sociedade", 2));
    cont_cHumans.Add(new Content(3, "Sociologia", "Modos de Produção", 2));
    cont_cHumans.Add(new Content(3, "Sociologia", "Mudança Social", 2));
    cont_cHumans.Add(new Content(3, "Sociologia", "Tecnologia", 2));
    cont_cHumans.Add(new Content(3, "Sociologia", "Mídia", 2));
    cont_cHumans.Add(new Content(4, "Filosofia", "Tales de Mileto", 2));
    cont_cHumans.Add(new Content(4, "Filosofia", "Sofistas", 2));
    cont_cHumans.Add(new Content(4, "Filosofia", "Sócrates", 2));
    cont_cHumans.Add(new Content(4, "Filosofia", "Platão", 2));
    cont_cHumans.Add(new Content(4, "Filosofia", "Aristóteles", 2));
    cont_cHumans.Add(new Content(4, "Filosofia", "Santo Agostinho", 2));
    cont_cHumans.Add(new Content(4, "Filosofia", "Tomás de Aquino", 2));
    cont_cHumans.Add(new Content(4, "Filosofia", "Maquiavel", 2));
    cont_cHumans.Add(new Content(4, "Filosofia", "Filósofos da Ciência", 2));
    cont_cHumans.Add(new Content(4, "Filosofia", "Descartes", 2));
    cont_cHumans.Add(new Content(4, "Filosofia", "Romantismo Alemão", 2));
    cont_cHumans.Add(new Content(4, "Filosofia", "Idealismo Alemão", 2));
    cont_cHumans.Add(new Content(4, "Filosofia", "Escola de Frankfurt da Teoria Crítica", 2));
  }
  public static void PopulatingCNature()
  {
    cont_cNature.Add(new Content(1, "Biologia", "Células Procariontes e Eucariontes",2));
    cont_cNature.Add(new Content(1, "Biologia", "Estrutura Química e o Metabolismo Celular", 2));
    cont_cNature.Add(new Content(1, "Biologia", "Membrana Plasmática", 2));
    cont_cNature.Add(new Content(1, "Biologia", "Permeabilidade Seletiva", 2));
    cont_cNature.Add(new Content(1, "Biologia", "Organelas", 2));
    cont_cNature.Add(new Content(1, "Biologia", "Respiração Aeróbica", 2));
    cont_cNature.Add(new Content(1, "Biologia", "Fermentação", 2));
    cont_cNature.Add(new Content(1, "Biologia", "DNA e RNA", 2));
    cont_cNature.Add(new Content(1, "Biologia", "Mitose e Meiose", 2));
    cont_cNature.Add(new Content(1, "Biologia", "Descartes", 2));
    cont_cNature.Add(new Content(1, "Biologia", "Classificação dos Seres Vivos", 2));
    cont_cNature.Add(new Content(1, "Biologia", "Filogenia", 2));
    cont_cNature.Add(new Content(1, "Biologia", "Nomenclaturas", 2));
    cont_cNature.Add(new Content(1, "Biologia", "Reino Monera", 2));
    cont_cNature.Add(new Content(1, "Biologia", "Reino Fungi", 2));
    cont_cNature.Add(new Content(1, "Biologia", "Reino Protista", 2));
    cont_cNature.Add(new Content(1, "Biologia", "Fotossíntese", 2));
    cont_cNature.Add(new Content(1, "Biologia", "Algas", 2));
    cont_cNature.Add(new Content(1, "Biologia", "Brióftas – Pteridófitas", 2));
    cont_cNature.Add(new Content(1, "Biologia", "Gimnospermas e Angiospermas", 2));
    cont_cNature.Add(new Content(1, "Biologia", "Raiz", 2));
    cont_cNature.Add(new Content(1, "Biologia", "Caule e Folha", 2));
    cont_cNature.Add(new Content(1, "Biologia", "Tecidos Vegetais", 2));
    cont_cNature.Add(new Content(1, "Biologia", "Célula Vegetal", 2));
    cont_cNature.Add(new Content(1, "Biologia", "Hormônios Vegetais", 2));
    cont_cNature.Add(new Content(1, "Biologia", "Movimentos Vegetais", 2));
    cont_cNature.Add(new Content(1, "Biologia", "Classificação dos Animais", 2));
    cont_cNature.Add(new Content(1, "Biologia", "Poríferos e Cnidários", 2));
    cont_cNature.Add(new Content(1, "Biologia", "Artrópodes", 2));
    cont_cNature.Add(new Content(1, "Biologia", "Moluscos", 2));
    cont_cNature.Add(new Content(1, "Biologia", "Equinodermo", 2));
    cont_cNature.Add(new Content(1, "Biologia", "Cordados: Peixes, Anfíbios, Répteis", 2));
    cont_cNature.Add(new Content(1, "Biologia", "Pele: Revestimento", 2));
    cont_cNature.Add(new Content(1, "Biologia", "Tecido Cartilaginoso, Ósseo e Muscular", 2));
    cont_cNature.Add(new Content(1, "Biologia", "Sistema Esquelético", 2));
    cont_cNature.Add(new Content(1, "Biologia", "Vitaminas e Sais Minerais", 2));
    cont_cNature.Add(new Content(1, "Biologia", "Sistema Digestório", 2));
    cont_cNature.Add(new Content(1, "Biologia", "Glândulas Anexas do Sistema Digestório", 2));
    cont_cNature.Add(new Content(1, "Biologia", "Tecido Sanguíneo", 2));
    cont_cNature.Add(new Content(1, "Biologia", "Sangue e Sistema Circulatório", 2));
    cont_cNature.Add(new Content(1, "Biologia", "Sistema Respiratório", 2));
    cont_cNature.Add(new Content(1, "Biologia", "Sistema Excretor", 2));
    cont_cNature.Add(new Content(1, "Biologia", "SNC e SNP", 2));
    cont_cNature.Add(new Content(1, "Biologia", "Sistema Endócrino", 2));
    cont_cNature.Add(new Content(1, "Biologia", "Imunização", 2));
    cont_cNature.Add(new Content(1, "Biologia", "Sis. Reprodutor Feminino", 2));
    cont_cNature.Add(new Content(1, "Biologia", "Sis. Reprodutor Masculino", 2));
    cont_cNature.Add(new Content(1, "Biologia", "Contracepção", 2));
    cont_cNature.Add(new Content(1, "Biologia", "Visão", 2));
    cont_cNature.Add(new Content(1, "Biologia", "Problemas de Saúde", 2));
    cont_cNature.Add(new Content(1, "Biologia", "Metabolismo da Glicose", 2));
    cont_cNature.Add(new Content(1, "Biologia", "Viroses", 2));
    cont_cNature.Add(new Content(1, "Biologia", "Doenças Bacterianas", 2));
    cont_cNature.Add(new Content(1, "Biologia", "Doenças protistas", 2));
    cont_cNature.Add(new Content(1, "Biologia", "Verminoses", 2));
    cont_cNature.Add(new Content(1, "Biologia", "Prevenção dos Alimentos", 2));
    cont_cNature.Add(new Content(1, "Biologia", "Contaminação da Água e Rios", 2));
    cont_cNature.Add(new Content(1, "Biologia", "Herança", 2));
    cont_cNature.Add(new Content(1, "Biologia", "Primeira Lei de Mendel", 2));
    cont_cNature.Add(new Content(1, "Biologia", "Heredrograma", 2));
    cont_cNature.Add(new Content(1, "Biologia", "Segunda Lei de Mendel", 2));
    cont_cNature.Add(new Content(1, "Biologia", "Herança e Determinação do Sexo", 2));
    cont_cNature.Add(new Content(1, "Biologia", "Grupos Sanguíneos", 2));
    cont_cNature.Add(new Content(1, "Biologia", "Mapas Genéticos", 2));
    cont_cNature.Add(new Content(1, "Biologia", "Biotecnologia e a Genética", 2));
    cont_cNature.Add(new Content(1, "Biologia", "Origem da Vida", 2));
    cont_cNature.Add(new Content(1, "Biologia", "Evidências da Evolução", 2));
    cont_cNature.Add(new Content(1, "Biologia", "Teorias da Evolução", 2));
    cont_cNature.Add(new Content(1, "Biologia", "Mutações gênicas", 2));
    cont_cNature.Add(new Content(1, "Biologia", "Evolução do Homem", 2));
    cont_cNature.Add(new Content(2, "Física", "Notação Científica e Ordem de Grandeza", 2));
    cont_cNature.Add(new Content(2, "Física", "Prefixos SIU", 2));
    cont_cNature.Add(new Content(2, "Física", "Unidades de Tempo, Comprimento, Área, Volume e Massa", 2));
    cont_cNature.Add(new Content(2, "Física", "Dimensão das Grandezas", 2));
    cont_cNature.Add(new Content(2, "Física", "Cinemática, Veloc. Escalar Média, Unidades de Velocidade", 2));
    cont_cNature.Add(new Content(2, "Física", "Movimento Uniforme (MU)", 2));
    cont_cNature.Add(new Content(2, "Física", "Aceleração Escalar Média (MUV)", 2));
    cont_cNature.Add(new Content(2, "Física", "Vazão e Velocidade", 2));
    cont_cNature.Add(new Content(2, "Física", "Movimento Vertical no Vácuo", 2));
    cont_cNature.Add(new Content(2, "Física", "Velocidade Angular", 2));
    cont_cNature.Add(new Content(2, "Física", "Lançamento Oblíquo", 2));
    cont_cNature.Add(new Content(2, "Física", "Lançamento Horizontal", 2));
    cont_cNature.Add(new Content(2, "Física", "Primeira e Segunda Lei de Newton", 2));
    cont_cNature.Add(new Content(2, "Física", "Polias", 2));
    cont_cNature.Add(new Content(2, "Física", "Plano Inclinado", 2));
    cont_cNature.Add(new Content(2, "Física", "Forças de Atrito", 2));
    cont_cNature.Add(new Content(2, "Física", "Força de Resistência do Ar", 2));
    cont_cNature.Add(new Content(2, "Física", "Força Elástica", 2));
    cont_cNature.Add(new Content(2, "Física", "Força Centrípeta", 2));
    cont_cNature.Add(new Content(2, "Física", "Trabalho", 2));
    cont_cNature.Add(new Content(2, "Física", "Energia Cinética", 2));
    cont_cNature.Add(new Content(2, "Física", "Energia Mecânica", 2));
    cont_cNature.Add(new Content(2, "Física", "Potência e velocidade", 2));
    cont_cNature.Add(new Content(2, "Física", "Potência e energia", 2));
    cont_cNature.Add(new Content(2, "Física", "Quantidade de Movimento", 2));
    cont_cNature.Add(new Content(2, "Física", "Impulso e Quantidade de Movimento", 2));
    cont_cNature.Add(new Content(2, "Física", "Colisões", 2));
    cont_cNature.Add(new Content(2, "Física", "Leis de Kepler", 2));
    cont_cNature.Add(new Content(2, "Física", "Gravitação Universal", 2));
    cont_cNature.Add(new Content(2, "Física", "Densidade de um corpo", 2));
    cont_cNature.Add(new Content(2, "Física", "Massa Específica", 2));
    cont_cNature.Add(new Content(2, "Física", "Lei de Stevin", 2));
    cont_cNature.Add(new Content(2, "Física", "Pressão Atmosférica", 2));
    cont_cNature.Add(new Content(2, "Física", "Princípio de Arquimedes", 2));
    cont_cNature.Add(new Content(2, "Física", "Temperatura: Escalas", 2));
    cont_cNature.Add(new Content(2, "Física", "Dilatação Linear", 2));
    cont_cNature.Add(new Content(2, "Física", "Dilatação Volumétrica", 2));
    cont_cNature.Add(new Content(2, "Física", "Dilatação Aparente", 2));
    cont_cNature.Add(new Content(2, "Física", "Calor Específico", 2));
    cont_cNature.Add(new Content(2, "Física", "Estados Físicos", 2));
    cont_cNature.Add(new Content(2, "Física", "Condução Térmica", 2));
    cont_cNature.Add(new Content(2, "Física", "Irradiação Térmica", 2));
    cont_cNature.Add(new Content(2, "Física", "Gases: Equações e Transformações", 2));
    cont_cNature.Add(new Content(2, "Física", "Termodinâmica", 2));
    cont_cNature.Add(new Content(2, "Física", "Máquinas Térmicas", 2));
    cont_cNature.Add(new Content(2, "Física", "Usinas", 2));
    cont_cNature.Add(new Content(2, "Física", "Corrente Elétrica", 2));
    cont_cNature.Add(new Content(2, "Física", "Resistência e Resistividade Elétrica", 2));
    cont_cNature.Add(new Content(2, "Física", "Associação de Resistores", 2));
    cont_cNature.Add(new Content(2, "Física", "Curto-Circuito", 2));
    cont_cNature.Add(new Content(2, "Física", "Potência Elétrica", 2));
    cont_cNature.Add(new Content(2, "Física", "Potência em Resistores", 2));
    cont_cNature.Add(new Content(2, "Física", "Eletrostática", 2));
    cont_cNature.Add(new Content(2, "Física", "Lei de Coulomb", 2));
    cont_cNature.Add(new Content(2, "Física", "Campo Elétrico e Campo Elétrico Uniforme", 2));
    cont_cNature.Add(new Content(2, "Física", "Condutor em Equilíbrio Eletrostático", 2));
    cont_cNature.Add(new Content(2, "Física", "Campo Magnético", 2));
    cont_cNature.Add(new Content(2, "Física", "Força Magnética", 2));
    cont_cNature.Add(new Content(2, "Física", "Fluxo Magnético", 2));
    cont_cNature.Add(new Content(2, "Física", "Óptica Geométrica", 2));
    cont_cNature.Add(new Content(2, "Física", "Espelhos Planos", 2));
    cont_cNature.Add(new Content(2, "Física", "Espelhos Esféricos", 2));
    cont_cNature.Add(new Content(2, "Física", "Refração da Luz", 2));
    cont_cNature.Add(new Content(2, "Física", "Lentes", 2));
    cont_cNature.Add(new Content(2, "Física", "Ondas", 2));
    cont_cNature.Add(new Content(2, "Física", "Acústica", 2));
    cont_cNature.Add(new Content(2, "Física", "Movimento Harmônico Simples", 2));
    cont_cNature.Add(new Content(3, "Química", "Estados Físicos da Matérias", 2));
    cont_cNature.Add(new Content(3, "Química", "Propriedades Físicas da Matéria", 2));
    cont_cNature.Add(new Content(3, "Química", "Densidade", 2));
    cont_cNature.Add(new Content(3, "Química", "Ar Atmosférico e Meio Ambiente", 2));
    cont_cNature.Add(new Content(3, "Química", "Estrutura do Átomo", 2));
    cont_cNature.Add(new Content(3, "Química", "Distribuição Eletrônica", 2));
    cont_cNature.Add(new Content(3, "Química", "Classificação dos Elementos", 2));
    cont_cNature.Add(new Content(3, "Química", "Fórmula Molecular", 2));
    cont_cNature.Add(new Content(3, "Química", "Fórmula Mínima", 2));
    cont_cNature.Add(new Content(3, "Química", "Fórmula Percentual", 2));
    cont_cNature.Add(new Content(3, "Química", "Massas Anatômicas", 2));
    cont_cNature.Add(new Content(3, "Química", "Massa Molecular", 2));
    cont_cNature.Add(new Content(3, "Química", "Proust e Lavoisier", 2));
    cont_cNature.Add(new Content(3, "Química", "Fenômenos Físicos e Químicos", 2));
    cont_cNature.Add(new Content(3, "Química", "Ligação Iônica", 2));
    cont_cNature.Add(new Content(3, "Química", "Ligação Covalente", 2));
    cont_cNature.Add(new Content(3, "Química", "Ligação Metálica", 2));
    cont_cNature.Add(new Content(3, "Química", "Propriedade dos Metais", 2));
    cont_cNature.Add(new Content(3, "Química", "Geometria Molecular", 2));
    cont_cNature.Add(new Content(3, "Química", "Forças Intermoleculares", 2));
    cont_cNature.Add(new Content(3, "Química", "Ácidos: Funções Inorgânicas", 2));
    cont_cNature.Add(new Content(3, "Química", "Bases", 2));
    cont_cNature.Add(new Content(3, "Química", "Óxidos", 2));
    cont_cNature.Add(new Content(3, "Química", "Sais: Salificação", 2));
    cont_cNature.Add(new Content(3, "Química", "pH", 2));
    cont_cNature.Add(new Content(3, "Química", "Soluções Químicas", 2));
    cont_cNature.Add(new Content(3, "Química", "Concentração de Soluções", 2));
    cont_cNature.Add(new Content(3, "Química", "Molaridade", 2));
    cont_cNature.Add(new Content(3, "Química", "Solubilidade", 2));
    cont_cNature.Add(new Content(3, "Química", "Tipos de Soluções", 2));
    cont_cNature.Add(new Content(3, "Química", "Propriedades Coligativas", 2));
    cont_cNature.Add(new Content(3, "Química", "Termoquímica", 2));
    cont_cNature.Add(new Content(3, "Química", "Cinética Química", 2));
    cont_cNature.Add(new Content(3, "Química", "Equilíbrio Químico", 2));
    cont_cNature.Add(new Content(3, "Química", "Oxidação e Redução", 2));
    cont_cNature.Add(new Content(3, "Química", "Eletroquímica", 2));
    cont_cNature.Add(new Content(3, "Química", "Eletrólise", 2));
    cont_cNature.Add(new Content(3, "Química", "Radioatividade", 2));
    cont_cNature.Add(new Content(3, "Química", "Isomeria Plana e Espacial", 2));
    cont_cNature.Add(new Content(3, "Química", "Química Orgânica", 2));
    cont_cNature.Add(new Content(3, "Química", "Funções Orgânicas", 2));
    cont_cNature.Add(new Content(3, "Química", "Petróleo", 2));
    cont_cNature.Add(new Content(3, "Química", "Reação de Combustão", 2));
    cont_cNature.Add(new Content(3, "Química", "Metano: Biogás", 2));
    cont_cNature.Add(new Content(3, "Química", "Polímeros", 2));
  }
  public static void PopulatingCMath()
  {
    cont_Math.Add(new Content(1, "Matemática", "Conjuntos Numéricos", 2));
    cont_Math.Add(new Content(1, "Matemática", "Expressões Numéricas", 2));
    cont_Math.Add(new Content(1, "Matemática", "Potências", 2));
    cont_Math.Add(new Content(1, "Matemática", "Equações", 2));
    cont_Math.Add(new Content(1, "Matemática", "Inequações", 2));
    cont_Math.Add(new Content(1, "Matemática", "Teoria dos Conjuntos", 2));
    cont_Math.Add(new Content(1, "Matemática", "Funções: Função Linear", 2));
    cont_Math.Add(new Content(1, "Matemática", "Tipos de Função", 2));
    cont_Math.Add(new Content(1, "Matemática", "Função Quadrática", 2));
    cont_Math.Add(new Content(1, "Matemática", "Grandezas Proporcionais: Porcentagem", 2));
    cont_Math.Add(new Content(1, "Matemática", "Funções Exponenciais: Funções Logarítmicas", 2));
    cont_Math.Add(new Content(1, "Matemática", "Progressões", 2));
    cont_Math.Add(new Content(1, "Matemática", "Análise Combinatória, Permutações, Arranjos, Combinação Simples", 2));
    cont_Math.Add(new Content(1, "Matemática", "Probabilidade", 2));
    cont_Math.Add(new Content(1, "Matemática", "Matrizes", 2));
    cont_Math.Add(new Content(1, "Matemática", "Sistema de Equações Lineares", 2));
    cont_Math.Add(new Content(1, "Matemática", "Trigonometria", 2));
    cont_Math.Add(new Content(1, "Matemática", "Geometria Analítica", 2));
    cont_Math.Add(new Content(1, "Matemática", "Sistema de Coordenadas", 2));
    cont_Math.Add(new Content(1, "Matemática", "Equações da Reta", 2));
    cont_Math.Add(new Content(1, "Matemática", "Circunferência", 2));
    cont_Math.Add(new Content(1, "Matemática", "Geometria Plana", 2));
    cont_Math.Add(new Content(1, "Matemática", "Geometria Espacial", 2));
    cont_Math.Add(new Content(1, "Matemática", "Prismas", 2));
    cont_Math.Add(new Content(1, "Matemática", "Estatística", 2));
    cont_Math.Add(new Content(1, "Matemática", "Raciocínio Matemático", 2));
  }
  public static void PopulatingLanguages()
  {
    cont_Languages.Add(new Content(1, "Português", "Fonética e Fonologia", 2));
    cont_Languages.Add(new Content(1, "Português", "Acentuação Gráfica", 2));
    cont_Languages.Add(new Content(1, "Português", "Significação das Palavras", 2));
    cont_Languages.Add(new Content(1, "Português", "Estrutura e Formação das Palavras", 2));
    cont_Languages.Add(new Content(1, "Português", "Pronomes", 2));
    cont_Languages.Add(new Content(1, "Português", "Conjunções", 2));
    cont_Languages.Add(new Content(1, "Português", "Interjeição", 2));
    cont_Languages.Add(new Content(1, "Português", "Sujeito e Predicado", 2));
    cont_Languages.Add(new Content(1, "Português", "Adjunto Adnominal/Adverbial/ Aposto e Vocativo", 2));
    cont_Languages.Add(new Content(1, "Português", "Orações Coordenadas", 2));
    cont_Languages.Add(new Content(1, "Português", "Orações Subordinadas", 2));
    cont_Languages.Add(new Content(1, "Português", "Pontuação", 2));
    cont_Languages.Add(new Content(1, "Português", "Figuras de Linguagem", 2));
    cont_Languages.Add(new Content(2, "Literatura", "Classicismo", 2));
    cont_Languages.Add(new Content(2, "Literatura", "Quinhentismo", 2));
    cont_Languages.Add(new Content(2, "Literatura", "Barroco", 2));
    cont_Languages.Add(new Content(2, "Literatura", "Arcadismo", 2));
    cont_Languages.Add(new Content(2, "Literatura", "Romantismo no Brasil", 2));
    cont_Languages.Add(new Content(2, "Literatura", "Realismo e Naturalismo no Brasil", 2));
    cont_Languages.Add(new Content(2, "Literatura", "Parnasianismo", 2));
    cont_Languages.Add(new Content(2, "Literatura", "Simbolismo", 2));
    cont_Languages.Add(new Content(2, "Literatura", "Pré-Modernismo", 2));
    cont_Languages.Add(new Content(2, "Literatura", "Modernismo", 2));
    cont_Languages.Add(new Content(2, "Literatura", "Pós-Modernismo", 2));
    cont_Languages.Add(new Content(2, "Literatura", "Modernismo no Brasil", 2));
    cont_Languages.Add(new Content(2, "Literatura", "Segunda Fase Modernista no Brasil", 2));
    cont_Languages.Add(new Content(2, "Literatura", "Carlos Drummond de Andrade", 2));
    cont_Languages.Add(new Content(2, "Literatura", "Terceira Fase do Modernismo no Brasil", 2));
    cont_Languages.Add(new Content(3, "Arte", "Body Art", 2));
    cont_Languages.Add(new Content(3, "Arte", "Art Digital", 2));
    cont_Languages.Add(new Content(3, "Arte", "Arte Perfomática", 2));
    cont_Languages.Add(new Content(3, "Arte", "Interação Entre Linguagens", 2));
    cont_Languages.Add(new Content(3, "Arte", "Instalação", 2));
    cont_Languages.Add(new Content(3, "Arte", "Hip Hop e Grafite", 2));
    cont_Languages.Add(new Content(3, "Arte", "Expressionismo", 2));
    cont_Languages.Add(new Content(3, "Arte", "Fauvismo", 2));
    cont_Languages.Add(new Content(3, "Arte", "Cubismo", 2));
    cont_Languages.Add(new Content(3, "Arte", "Dadaísmo", 2));
    cont_Languages.Add(new Content(3, "Arte", "Surrealismo", 2));
    cont_Languages.Add(new Content(3, "Arte", "Semana de Arte Moderna", 2));
    cont_Languages.Add(new Content(3, "Arte", "Fotografias e Fotogramas", 2));
    cont_Languages.Add(new Content(3, "Arte", "Ópera do Século XIX", 2));
    cont_Languages.Add(new Content(3, "Arte", "Cerâmica majoara;", 2));
    cont_Languages.Add(new Content(3, "Arte", "Colagem e Decollage", 2));
    cont_Languages.Add(new Content(3, "Arte", "Xilogravura nordestina", 2));
  }

}
